[tool.poetry]
name = "ocpp"
version = "0.1.1"
description = "Python package implementing the JSON version of the Open Charge Point Protocol (OCPP)."
authors = [
	"Auke Willem Oosterhoff <aukewillem.oosterhoff@mobilityhouse.com>"
]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.6"

# The dataclasses module is not in the stdlib in Python 3.6.
dataclasses = { version = "^0.6", python = "~3.6" }
jsonschema = "^3.0"

[tool.poetry.dev-dependencies]
pytest = "^4.5"
pytest-asyncio = "^0.10.0"
asynctest = "^0.13.0"
freezegun = "^0.3.12"
flake8 = "^3.7"
pytest-cov = "^2.7"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
